//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class Arabes : MonoBehaviour
{
	private float puntuacion = 0;
	[SerializeField]
	private Transform reiniciar;
	

	void Update()
	{
		puntuacion += Time.deltaTime;
	}

	public void Perder()
	{
		reiniciar.gameObject.SetActive(true);
		Time.timeScale = 0;
	}

	public float Puntuacion
	{
		get {return puntuacion;}
	}

	public void Reset() 
	{
		FindObjectOfType<ControlGameObject> ().OnApplicationPause (true);
		Time.timeScale = 1;
		Application.LoadLevel(1);
	}
}

