//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;

public class Obstaculo : MonoBehaviour
{
	[SerializeField]
	public float _velocidad;

	void Update()
	{
		transform.position = new Vector3(transform.position.x, 
		                                 transform.position.y - _velocidad * Time.deltaTime,
		                                 0);
	}

	void OnCollisionEnter2D(Collision2D col)
	{
		if (col.gameObject.tag == "Player")
		{
			FindObjectOfType<Arabes>().Perder();
		}
	}
}

